export type Article = {
  title: string
  description: string
  category: string
  mainImage: string
  id: number
  heading: string
  images?: string[]
  content?: string[]
  date?: string
  author?: string
  photographer?: string
}

const ArticlesArray: Article[] = [
  {
    id: 1,
    title: 'Kennedy Yanko’s Poetic Fusion of Metal and “Paint Skin”',
    description:
      'This new exhibition at the Patrick Parrish Gallery in New York City showcases an impressive list of 42 artists and designers.',
    category: 'art',
    heading: 'featured',
    mainImage: '/images/Kennedy_Yanko_Jeffrey_Deitch.jpg',
    images: [
      '/images/Kennedy-Yanko-Fusion/Kennedy_Yanko_Jeffrey_Deitch_02.jpg',
      '/images/Kennedy-Yanko-Fusion/Kennedy_Yanko_Jeffrey_Deitch_01.jpg',
      '/images/Kennedy-Yanko-Fusion/Kennedy_Yanko_Jeffrey_Deitch_05.jpg',
      '/images/Kennedy-Yanko-Fusion/Kennedy_Yanko_Jeffrey_Deitch_07.jpg',
      '/images/Kennedy-Yanko-Fusion/Kennedy_Yanko_Jeffrey_Deitch_08.jpg',
      '/images/Kennedy-Yanko-Fusion/Kennedy_Yanko_Jeffrey_Deitch_06.jpg',
    ],
    content: [
      'Brooklyn-based artist Kennedy Yanko uses salvaged metal and blanket-like “paint skins” to create incredible artworks that challenge the definition of painting and perfectly balance a range of oppositions. Her current exhibition Humming on Life presents 10 new artworks on view at Jeffery Deitch in New York through April 22nd.',
      'Metal feels weightless, refuse becomes beautiful, and paint breaks free from canvas. The “paint skins” in Yanko’s work are literally just paint – first created flat and then draped over, between, and within the crushed metal. The fabric-like folds and crushed-metal dents echo each other while both feel organically matched – as if the two elements have somehow grown together.',
      'These new 2023 works add a new layer to her process. On previous works, the color of the paint skins was inspired by an existing color on the found metal: perhaps a lime green from oxidized copper or a burgundy from a small patch of rust. But in these new works, Kennedy has introduced the act of painting onto the metal itself with more colors before pieces are fire-cut and additionally crushed. This process introduces more complex color interactions while maintaining a contrast of time and texture between the elements.',
    ],
    date: '03.23.23',
    author: 'David Behringer',
    photographer: 'Martin Parsekian',
  },
  {
    id: 2,
    title: 'Designed in Poland: Lodz Design Festival',
    description:
      "The Nivél Pendant's flat panel LED light pivots on an axis to focus light downward or as a soft wall wash.",
    category: 'home furnishing',
    heading: 'featured',
    mainImage: '/images/Pablo-Designs-Nivel-Pendant.jpg',
    images: [
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_02.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_03.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_04.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_05.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_07.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_09.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_10.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_11.jpg',
      '/images/Lodz-Design-Festival/Lodz_Design_Festival_14.jpg',
    ],
    content: [
      'Once more closely associated with production and manufacturing, Poland is emerging as a real contender when it comes to design – “Designed in Poland” is starting to mean as much as “Made in Poland”. I headed over to Lodz (pronounced Woodge!) Design Festival to find out more. One of the highlights was meeting Polish design superstar Oskar Zieta.',
      'It was great to see Oskar’s Plopp Chair (an iteration of the iconic Plopp Stool) alongside British designer Tom Dixon’s pendant lights – copper is clearly en vogue! Oskar was there to share his newest technology – he seam welds two sheets of metal together and the user receives the product flat-packed and sealed with the ‘secret potion’ locked inside. When heated to a temperature of 200ºC, which the customer can do at home, the product transforms from a two-dimensional object into a bulbous, three-dimensional form. It was a lot of fun watching him demonstrate!',
      'Slightly subverting the festival’s theme of Brave New World, Daniel Charny, Director at London design studio From Now On, curated an exhibition called Brave New Fixed World, to counter the ‘ending is better than mending’ slogan of the Aldous Huxley novel. Above: Sugru, a self-setting rubber that can be hand-formed, bonds to almost anything and turns into a strong, flexible silicone rubber overnight.',
    ],
    date: '11.05.14',
    author: 'Katie Treggiden',
    photographer: ' Alicja Patanowska',
  },
  {
    id: 3,
    title:
      'Tekla Evelina Severin Drops Color-Blocking "Colour Vibes" at FORMEX',
    description:
      'Working with the theme of "Colour Vibes," color phenom Tekla Evelina Severin transforms empty space into surreal, color-blocked exhibition.',
    category: 'interrior design',
    heading: 'featured',
    mainImage: '/images/Dimensions-of-Colour-Formex.jpg',
    images: [
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-1.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-2.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-3.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-4.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-5.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-6.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-7.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-8.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-14.jpg',
      '/images/Tekla-Evelina-Severin/Dimensions-of-Colour-Formex-Tekla-Evelina-Severin-15.jpg',
    ],
    content: [
      'Working with the theme of “Colour Vibes,” color and design phenom Tekla Evelina Severin transformed a 250-square-meter (almost 2,700 square feet) empty space for the FORMEX interior fair last month. The project involved exhibition design, curation, and styling a series of rooms, which resemble either a beautifully staged set for a magazine photo shoot or a perfectly executed interior of a home. Taking inspiration from a labyrinth, hide-and-seek games, and a Rubik’s cube, Dimensions of Colour consists of multiple spaces placed in a zigzag formation, allowing for changes in perspective from every view. No matter the angle, new framed vignettes appear, as do ever-changing color palettes, making the space feel like it’s bouncing back and forth between realism and surrealism.',
      'Immersed in Severin’s color-blocked world are a curated roster of 200 products sourced from 400 exhibitors, resulting in a broad mix of objects that feel like they belong.',
      'Each space features black and white checkered floors with layers of rich, saturated wall colors. Topped off with furnishings – some that match and some that contrast – that give each room a purpose, whether it’s a living room, kitchen, bedroom, kid’s space, atrium, or living room.',
    ],
    date: '02.21.23',
    author: 'Caroline Williamson',
    photographer: 'Fredrik Bengtsson and Tekla Evelina Severin',
  },
  {
    id: 4,
    title: 'Listen to the KBIS 2023 DMM Talks Lounge Panels Online',
    description:
      'Listen to all of the panel conversations that happened in the DMM Talks Lounge at KBIS 2023.',
    category: 'featured',
    heading: 'featured',
    mainImage: '/images/KBIS-2023-DMM-Talks-Lounge.jpg',
    images: [
      '/images/KBIS-2023-DMM-Talks/dmmtalks-2020-lounge-kbis.jpg',
      '/images/KBIS-2023-DMM-Talks/kbis-2023-round-up-2.jpg',
      '/images/KBIS-2023-DMM-Talks/kbis-2023-round-up-5.jpg',
      '/images/KBIS-2023-DMM-Talks/kbis-2023-round-up-11.jpg',
      '/images/KBIS-2023-DMM-Talks/kbis-2023-SKS-fridge-1.jpg',
      '/images/KBIS-2023-DMM-Talks/kbis-2023-SKS-fridge-3.jpg',
    ],
    content: [
      'The fifth (!) Design Milk X Modenus Talks (#DMMTalks) lounge at KBIS is back IRL! Register here. We are super excited to be there to host all these fantastic events, plus I’ll be moderating not one, but TWO Trends talks that you don’t want to miss!',
      'Do you know that your website is the only piece of digital real estate that you actually own? All other social platforms are subject to algorithm changes, freemium business models, and simply at the discretion of the companies that own them. Learn from web design guru Nicole Heymer of Glory & Brand what it takes to optimize your website, your content, and search engine strategy in order to stay in control of your digital footprint.',
      'Processes and systems are important to every business, whether you are a kitchen and bath designer, interior designer, or a web designer. Business is business and well-run businesses have systems in place. But, the current global economy has wreaked havoc on the home industry businesses, so systems are more critical than ever. Join LuAnn Nigara as she outlines the 3 non-negotiable systems you need to up level and streamline, now, in order to be successful in this new business climate.',
      'It’s time to re-imagine what the American Kitchen is and should be – a true intersection of personal and planetary health. This intimate conversation aims to serve as a resource to designers and builders who wish to offer their clients ways to accomplish a healthier, more sustainable kitchen and home by the fastest growing and most sustainable home appliance brand in the U.S. Join Modenus Media CEO Veronika Miller in conversation with Beko Home Appliances President and 2022 Kitchen & Bath Industry Hall of Fame Inductee Zach Elkin.',
    ],
    date: '01.21.22',
    author: 'Jaime Derringer',
    photographer: 'Lefroy Brooks',
  },
  {
    id: 5,
    title: "Charles Gaines' Colorful Pixelation of Southern Trees",
    description:
      "Conceptual artist Charles Gaines presents new colorful pixelated abstractions of 'Southern Trees' in New York.",
    category: 'art',
    heading: 'featured',
    mainImage: '/images/Charles-Gaines-Southern-Trees.jpg',
    images: [
      '/images/Colorful-Pixelation/Charles-Gaines-Southern-Trees-Hauser-Wirth-closeup.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_01.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_03.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_06.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_09.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_10.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_12.jpg',
      '/images/Colorful-Pixelation/Charles_Gaines_Hauser_Wirth_17.jpg',
    ],
    content: [
      'Artworks can provide an immediate rush of joy on first impression, or slowly build in appreciation over multiple visits. Charles Gaines’ current exhibition at Hauser & Wirth Gallery in New York does both: it is breathtaking from the moment you walk in, and offers new discoveries and deeper fulfillment with every subsequent visit. The artworks are individually brilliant while they also connect to each other in a series that invites you to get closer while extending your peripheral vision.',
      'The exhibition’s title “Southern Trees” references the 150-year-old pecan trees shown in the 17 new works – all photographed on a visit to Boone Hall Plantation in Charleston County, South Carolina, not far from where the artist was born.',
      'The exhibition crescendos as each work builds on the last. For example, the first watercolor seen in the gallery is a single tree from start to finish (in blue), followed by the second work in the exhibition that adds a tree (red) to that equation. A new tree is presented in the photograph and silhouette alone, but is added to the first tree in the watercolor. The third work introduces a third tree, and so on. By the time you walk to the 7th and 8th work in the room, the forms and colors fuse together in an abstraction that celebrates difference as a whole. ',
      'Even when the layered colors are the exact same within a single square, the final color within each square (a brown or green, etc.) is always different due to the variance of pigment saturation in every application.',
    ],
    date: '02.21.23',
    author: 'David Behringer',
    photographer: 'Sarah Muehlbauer',
  },

  {
    id: 6,
    title:
      'You Can Now Customize Samsung Bespoke Refrigerators With Any Image (*For a Price)',
    description:
      'Samsung has unlocked unlimited possibilities by allowing customers to upload any image, design, or photo to adorn their Bespoke fridges.',
    category: 'technology',
    heading: '',
    mainImage: '/images/Generative-Art-Collection.jpg',
    images: [
      '/images/Samsung-Bespoke-Refrigerators/Generative-Art-Collection-3.jpg',
      '/images/Samsung-Bespoke-Refrigerators/Generative-Art-Collection-5.jpg',
      '/images/Samsung-Bespoke-Refrigerators/Samsung_MyBespoke_Eero-Screenshot-2023-02-02-at-8.38.05-PM.jpg',
      '/images/Samsung-Bespoke-Refrigerators/Samsung_MyBespoke_Generative.jpg',
      '/images/Samsung-Bespoke-Refrigerators/MyBespoke_Kitchens.jpg',
    ],
    content: [
      'Slowly, but surely colors are finally seeping back into the kitchen with more visual impact beyond small appliances or subtly shaded cabinetry. In our previous coverage of Samsung’s Bespoke offerings we’ve lauded the Korean company’s efforts to establish themselves as the bold outliers within the kitchen appliance category, adorning the largest kitchen appliance in the home with bold hues and even artwork, abandoning the staid standards of a typical black, white, or stainless steel kitchen format.',
      'Yet, I’ve bemoaned the lack of additional options. More colors, please! Well, Samsung seems to have heard the clamoring for additional options, responding in kind with their first-ever Bespoke refrigerator offering image personalization using nearly any uploaded original design, artwork, or photo using Samsung’s MyBespoke online customization tool.',
      'Of course, we had to test this customization feature with a photo from our personal archives, our Bespoke refrigerator emblazoned with a “favorite photo on the fridge” theme taken to its largest extreme.',
      'MyBespoke fridge panel customization is now available for one or both French Doors, with the option to assign separate images to each panel door or to designate a single image to adorn the surface across both doors. Other adjoining lower panels can be further customized in colors to complement your truly bespoke kitchen appliance.',
    ],
    date: '02.03.23',
    author: 'Gregory Han',
    photographer: 'Sarah Muehlbauer',
  },
  {
    id: 7,
    title: 'A Modern Red House in Sweden Near the Arctic Circle',
    description:
      'Due to strict zoning rules, this angular house required a red roof which led to the designers wrapping the rest of the house in the same bold color.',
    category: 'architecture',
    heading: '',
    mainImage: '/images/Arctic-Circle-House-Sweden.jpg',
    images: [
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-1.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-2.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-3.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-5.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-8.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-9.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-12.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-14.jpg',
      '/images/Red-House-in-Sweden/Arctic-Circle-House-Sweden-Claesson-Koivisto-Rune-19m.jpg',
    ],
    content: [
      'Claesson Koivisto Rune allowed the super strict zoning regulations guide the design of this modern red house just south of the Arctic Circle in Northern Sweden. Located next to the Lule River, the Simonsson House stands under the 4.2-meter maximum building height and is finished off with a matching red roof, which was required by law. To further the home’s sculptural design, the red was carried down to the actual house for a uniform appearance.',
      'The Simonsson House is made up of two trapezoidal volumes that face opposite directions, each with a single pitch roof. The roof design allows for the second story and to maximize views of the river.',
      'The smaller volume includes a cutout in the roof for a second floor deck to enjoy the surrounding landscape. The volume also houses the garage and sauna.',
      'Complementing the simplicity of the exterior’s design, the inside has a minimalist aesthetic with wood being the standout material throughout. While the outside is clad in bold red panels, the interior features toned down shades of grey.',
      '',
    ],
    date: '02.13.23',
    author: 'Caroline Williamson',
    photographer: 'Åke E:son Lindman',
  },
  {
    id: 8,
    title:
      "A Lighting Collection Inspired by Frank Lloyd Wright's Iconic Architecture",
    description:
      "The Frank Lloyd Wright series for YAMAGIWA includes representations of a few of the legendary architect's original masterpieces in the form of lighting.",
    category: 'home furnishing',
    heading: '',
    mainImage: '/images/Frank-Lloyd-Wright-Lighting-Collection.jpeg',
    images: [
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA.jpeg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Taliesin-2-Black.jpeg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Taliesin-2-Oak.jpg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Taliesin-2-Oak-.jpg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Taliesin-2-Oak-1-1.jpg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Taliesin-4-Cherry.jpg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Taliesin-Pendant-11.jpg',
      '/images/Lighting-Collection-by-Frank-Lloyd-Wright/Frank-Lloyd-Wright-Lighting-Collection-YAMAGIWA-Robie-1-Cherry-810x810.jpg',
    ],
    content: [
      'Frank Lloyd Wright keeps on giving us more, even from the great beyond. Today, it’s the Frank Lloyd Wright series that includes representations of a few of the architect’s original masterpieces in the form of lighting. The licensed collection from YAMAGIWA hones in on Wright’s refined style known for highlighting the relationships that can be found between natural and manmade elements – “Organic Architecture.”',
      'Out of the three Taliesin pendant lights in this series, Taliesin Pendant 3 is our favorite. It was originally designed to be included in the renovation of the gymnasium of Wright’s Hillside home school when it was turned into a theatre in 1935. Without the inclusion of glass or shades, the suspended pendant light uses wooden boxes and plywood shields to reduce glare. Hang it from the highest ceiling for a true statement.',
      'Designed for the living room of the Frederik Robie House in Chicago, the ROBIE wall sconce borrows elements from Wright’s early prairie house style days. The glass globe all but floats within the wooden frame of the lighting piece, whose influence is still recognizable with the addition of all of those sharp wooden angles.',
      'The Special Limited Model of the Taliesin Polygon, designed by Toyo Ito, pays homage to the legend himself. Ito used Wright’s Taliesin 2 as his starting point, translating it into a new version of the architect’s ideas and motifs from a fresh perspective.',
    ],
    date: '02.03.23',
    author: 'Kelly Beall',
    photographer: 'Sarah Muehlbauer',
  },
  {
    id: 9,
    title:
      'The Shinola Hotel Is Built in Detroit by Locals Shinola and Bedrock',
    description:
      "Shinola Hotel is a boutique hotel in Detroit with a hyper-local design that's evident everywhere, from ceramic wall tiles to millwork made by local merchants.",
    category: 'travel',
    heading: '',
    mainImage: '/images/shinolahotel_shinola.jpg',
    images: [
      '/images/The-Shinola-Hotel/shinolahotel_shinola_1.jpg',
      '/images/The-Shinola-Hotel/shinolahotel_shinola_2.jpg',
      '/images/The-Shinola-Hotel/shinolahotel_shinola_5.jpg',
      '/images/The-Shinola-Hotel/shinolahotel_shinola_6.jpg',
      '/images/The-Shinola-Hotel/shinolahotel_shinola_10.jpg',
      '/images/The-Shinola-Hotel/shinolahotel_shinola_12.jpg',
      '/images/The-Shinola-Hotel/shinolahotel_shinola_14.jpg',
    ],
    content: [
      'Shinola Hotel is a boutique hotel located in Detroit, Michigan, built by Shinola and Bedrock. The property boasts 129 rooms and includes four food and beverage concepts from award-winning chef, Andrew Carmellini. The hotel’s hyper-local design is evident everywhere, from ceramic wall tiles and millwork made by local merchants to mini bars stocked with local goods and Detroit-designed wallpaper.',
      'Aiming to be a gathering place for both residents of Detroit and tourists, the main living room space offers a warm and inviting setting for a meeting over lunch, drinks, or a late-night snack. The residential-style guest rooms and suites have hardwood floors and comfortable mid-century contemporary furnishings. Loft-style windows offer abundant natural light while earthy tones create a relaxing ambience.',
      'The hotel features an award-winning restaurant, San Morello, serving authentic wood-fired cuisine, house-made pastas, and pizzas crafted using local, seasonal ingredients. The floor is made of stone and has a checkerboard pattern in Rojo Alicante and Crema Ella with inset oak and bronze accents.',
    ],
    date: '12.01.22',
    author: 'Leo Lei',
    photographer: 'Nicole Franzen',
  },
  {
    id: 10,
    title: 'New Book Release: The Brutalists: Brutalism’s Best Architects',
    description:
      "Author Owen Hopkins highlights more than 250 Brutalist architects in the new release The Brutalists: Brutalism's Best Architects.",
    category: 'architecture',
    heading: '',
    mainImage:
      '/images/The-BrutalistsBrutalisms-Best-Architects-Owen-Hopkins.jpg',
    images: [
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-Featured-Image.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-2.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-3.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-Bogdanovic-4.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-Contigiani-5.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-Dieste-6.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-Vasilevsky-7.jpg',
      '/images/The-Brutalists/The-Brutalists-Brutalisms-Best-Architects-Owen-Hopkins-Phaidon-Warren-Mahoney-8.jpg',
    ],
    content: [
      'If there’s one thing we can all agree on when it comes to Brutalism, it’s that it’s unquestionably divisive. Since its inception in 1936, people have either loved or loathed the architectural style with very little grey space in between. What can’t be denied is that the style has produced some of the world’s most interesting buildings.',
      'Author Owen Hopkins has taken on the task of whittling down a list of Brutalist architects to highlight in The Brutalists: Brutalism’s Best Architects, published by Phaidon. That number is somewhere north of 250 individuals, with each profile including selected samples of their work and a short biography/introduction. From international icons to lesser known or neglected Brutalist architects, Hopkins has created a written record of the global movement.',
      'During the year it took Hopkins to research and write “The Brutalists” he realized just how pertinent the school’s ideology remains today. “The Brutalists believed that architecture had the power to remake the world for the better,” he said. “Given the myriad challenges we face collectively as a society, it’s an ambition we urgently need to recapture.”',
    ],
    date: '02.22.23',
    author: 'Kelly Beall',
    photographer: 'John Millard',
  },
  {
    id: 11,
    title:
      'Our Place Opens Melrose Retail Spot With Colors That Reflect Their Pans',
    description:
      'Our Place hired Ringo Studio to create a store with visually delightful product displays and a color palette that matches their popular pans.',
    category: 'commercial',
    heading: '',
    mainImage: '/images/Our-Place-Melrose.jpg',
    images: [
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-1.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-2.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-3.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-5.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-6.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-7.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-9.jpg',
      '/images/Melrose-Retail-Spot/Our-Place-Melrose-Retail-Shop-Ringo-Studio-10.jpg',
    ],
    content: [
      'If you’ve spent any amount of time on social media the past three years, chances are you’ve run across the cookware brand Our Place. Founded in 2019 by Shiza Shahid, the direct-to-consumer brand has grown from its start-up days to now opening up their second Los Angeles retail location in West Hollywood. After the success of their Mythology-designed Venice location, Our Place turned to Ringo Studio to create a new store on Melrose that complements their designs and ethos. Alongside visually delightful product displays and a color palette that matches the colors of their popular pans, the space includes the Building a Bigger Table Room that exudes their mission to “welcome everyone to have a seat at the table.”',
      'The store is designed as a one-stop shop where customers can check out the brand’s cookware, tableware, and kitchen tools up close. The home-like atmosphere features curated product vignettes that make each piece stand out, almost like a sculptural piece of art.',
      'While the brand started with just one product – the Always Pan – they’ve expanded their line to include the newer Mini Always Pan, Perfect Pot, Mini Perfect Pot, Ovenware Set, dinnerware, drinkware, serveware, and kitchen tools.',
    ],
    date: '02.02.23',
    author: 'Caroline Williamson',
    photographer: 'Jenna Peffley',
  },
  {
    id: 12,
    title: 'F5: Melanie Courbet Shares the Spark Behind Her Gallery + More',
    description:
      "Gallery founder + director Melanie Courbet shares a worthwhile organization in Sierra Leone, the place she just can't stop shopping + more in Friday Five.",
    category: 'art',
    heading: '',
    mainImage: '/images/F5-Melanie-Courbet.jpg',
    images: [
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Contourline.jpg',
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Portrait.jpg',
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Metropolitan-Museum-of-Art.jpg',
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Maison-Integre.jpg',
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Moon-Sofa-Raphael-Navot.jpg',
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Nakagawa-Mokkougei-Indigo-Table.jpg',
      '/images/F5-Melanie-Courbet/F5-Melanie-Courbet-Vessels-Karen-Swami-Collection.jpg',
    ],
    content: [
      'Influenced by her French and Tunisian upbringing, travels and collaborations, Melanie Courbet founded Les Ateliers Courbet in 2013. The Founder of the gallery, located in the Chelsea neighborhood, chose to focus on a master-craftsman ethos and the sharing of art that embodies artisanal dexterity and cultural heritage. Les Ateliers Courbet comes with international recognition for its dedication to craftsmanship legacies and techniques that have stood the test of time. Today, the gallery represents a permanent roster of more than 30 ateliers whose works reside in the decorative arts and furniture. Melanie works with private collectors, interior designers, and public institutions to foster and share the work of these sometimes centuries-old manufacturers and international contemporary artisans.',
      'Before making the jump and owning her own gallery space, Melanie worked in Los Angeles advising young collectors, managing design projects, and organizing exhibitions in New York and Paris. She also incubated the Love & Art for Children Foundation and managed design studio Dror’s international communications and business development. All of the pieces were there, she just had to put them together.',
      'Melanie has had the opportunity to collaborate with some established names and brands, among them are LVMH, Cappellini, Christie’s, and Pritzker Prize Architect, Thom Mayne. Institutions include the Muséedes Arts Décoratifs in Paris, the Los Angeles Department of Cultural Affairs, and the Ministry Of Culture in France.',
    ],
    date: '02.03.23',
    author: 'Kelly Beall',
    photographer: 'Melanie Courbet',
  },
  {
    id: 13,
    title:
      'An Apartment on a Residential Yacht That Transforms From One Bedroom to Two',
    description:
      "Michael K. Chen Architecture designed a transforming Pied-å-Mer that serves as a couple's holiday retreat located aboard a residential yacht.",
    category: 'architecture',
    heading: '',
    mainImage: '/images/MKCA_Pied-a-Mer-Apartment.jpg',
    images: [
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-1.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-2.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-3.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-4.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-5.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-7.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-9.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-9m.jpg',
      '/images/Residential-Yacht/MKCA_Pied-a-Mer-Apartment-at-Sea-13.jpg',
    ],
    content: [
      'It might look like a regular residence at first glance, but this 600-square-foot apartment is located aboard a residential yacht. Designed by Michael K. Chen Architecture (MKCA), the Pied-å-Mer serves as a couple’s holiday retreat for themselves and their grown children as it easily transforms to welcome two to four people. MKCA utilized their own knowledge in designing smaller, multifunctional spaces, while referencing Le Corbusier’s fascination with mid-century steamship design to create the clever convertible floor plan.',
      'The apartment incorporates convertible designs, like fold-up beds and a collapsing dining table. The main living area features two ribbed aluminum pod-like structures that help organize the space while housing two bathrooms and storage. The open living room turns into the primary bedroom when a cantilevered bed pulls down. A passageway against the wall leads to the main bathroom and closet, which is easily accessed from the bedroom.',
      'A seating area on the opposite side of the apartment transforms to a dining area when it’s time to eat, and then to a second bedroom when needed. A sliding screen surrounds it to give both beds privacy.',
    ],
    date: '11.03.22',
    author: 'Caroline Williamson',
    photographer: 'Alan Tansey',
  },
  {
    id: 14,
    title: 'Business of Design Week 2022 Drives Innovations Amid Uncertainty',
    description:
      "On the occasion of the summit's 20th anniversary, Business of Design Week 2022 will be a celebration with creative leaders under the theme 'Design for Change.'",
    category: 'featured',
    heading: '',
    mainImage: '/images/Business-of-Design-Week-2022-Nikki-Gonnissen.jpg',
    images: [
      '/images/Design-Week-2022/Business-of-Design-Week-2022.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Adeline-Ooi-Art-Basel-6.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Chi-Wing-Lo-Glass-House-2.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Dr-Paul-Thompson-3.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Koen-Olthuis-SEA-TREE-4.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Richard-Hutten-7.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Ross-Lovegrove-5.jpg',
      '/images/Design-Week-2022/Business-of-Design-Week-2022-Chi-Wing-Lo-The-Ark-of-World-Poetry-8.jpg',
    ],
    content: [
      'Business of Design Week (BODW) 2022, Asia’s premier annual event covering design, innovation, and brands, returns this month as an in-person event for the first time since 2018! On the occasion of the summit’s 20th anniversary, November 28th through December 3rd will be a celebration marked by illuminating conversations with creative leaders under the theme ‘Design for Change.’ The 4-day summit will welcome international speakers Chi Wing Lo, Richard Hutten, Ross Lovegrove, Nikki Gonnissen, Rossana Hu, Bill Bensley, Sylvain Roca, and more, from the United Kingdom, France, Thailand, Japan, Korea, and the Netherlands, which is also the summit’s Strategic Partner this year.',
      'Since 2002, BODW has been gathering the brightest creative leaders and design-related initiatives together in Hong Kong, making it a much-anticipated event. By partnering with 13 countries over the past 20 years, it’s also strengthened collaborations across borders. The theme, ‘Design for Change,’ highlights the vision and leadership required for design to become a force for good while defining key movements and future trends.',
      'BODW 2022 will focus on five main pillars: Brand Transformation, Culture and the City, Metaverse and Metaliving, New Urban Models, and Social Design Innovation. Global business and design leaders representing some of the world’s most innovative brands will be on hand to share their thoughts on how upcoming trends can help businesses take on change with a design mindset. Such a conversion can empower more socially and environmentally responsible, resilient practices.',
    ],
    date: '11.28.22',
    author: 'Kelly Beall',
    photographer: 'Nikki Gonnissen',
  },
  {
    id: 15,
    title: 'Relevo Rug Sculpts a Welcoming Geometric Landscape Underfoot',
    description:
      "Light and shadow come to play across Milan-based Studiopepe's Relevo, a new hand-tufted, sculptural wool rug design for Muuto.",
    category: 'home furnishing',
    heading: '',
    mainImage: '/images/Muuto-relevo.jpg',
    images: [
      '/images/Relevo-Rug-Sculpts/Muuto-connect-soft-corner-config.jpg',
      '/images/Relevo-Rug-Sculpts/Muuto-relevo-170x240-off-white-oslo-lounge-chair-colline-swivel-base.jpg',
      '/images/Relevo-Rug-Sculpts/Muuto-relevo-rug-burnt-orange-dark.jpg',
      '/images/Relevo-Rug-Sculpts/Muuto-relevo-rug-dark-green-sage-green-burnt-orange.jpg',
      '/images/Relevo-Rug-Sculpts/Muuto-relevo-sage-green-170x240-in-situ-3-seater-config-8-vidar-693-strand.jpg',
    ],
    content: [
      'A rug at its most basic exists merely as a floor cover, protecting the surface and also to provide occupants an agreeable material to tread upon. But a rug of note can be a transformative, if not an artful expression within a room. Muuto’s Relevo Rug designed by Milan-based design duo Studiopepe represents the latter, a beautifully hand-tufted sculptural wool rug with an elevated attention to detail in its color, texture, and dimensions.',
      'Derived from the word for “relief” in Latin, the Relevo presents itself as an engaging sculptural plane of New Zealand wool, trimmed to differing levels and channeled widths, resulting in a dynamic geometric and graphic pattern.',
      'Like the raked sand or gravel of a Japanese karesansui garden, the topography realized in soft wool offers an engaging visual element beyond singular color, with the rug presenting an interplay of tones dependent upon light and shadow as the daylight or interior light source changes. But where raked gravel of a karesansui garden is strictly off-limits, the Relevo invites footfall with texture and soft touch.',
    ],
    date: '02.02.23',
    author: 'Gregory Han',
    photographer: 'Muuto’s Relevo',
  },
  {
    id: 16,
    title: "3form's 2023 Color Collection Nails Down Hard-to-Find Hues",
    description:
      "The 10 new pastel colors are inspired by the four seasons and will be permanently added to 3form's color system.",
    category: 'commercial',
    heading: '',
    mainImage: '/images/3form-2023-color-collection.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 17,
    title: 'Two Levitating, Rammed Earth Villas in a Costa Rican Jungle',
    description:
      'In the Costa Rican jungle, a pair of jaw-dropping, minimalist villas with rammed earth walls awaits you on your next vacation.',
    category: 'travel',
    heading: '',
    mainImage: '/images/Achiote-Formafatal-Rammed.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 18,
    title: 'A Melbourne House With 10 Folds in the Roof To Bring in Light',
    description:
      'A home in Melbourne with an Edwardian front facade is renovated and given a back extension complete with ten folds in its roof to bring in light.',
    category: 'architecture',
    heading: '',
    mainImage: '/images/10-Fold-House-Timmons.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 19,
    title: 'Lee Broom Exhibits Within the "British Capsule" at Maison&Objet',
    description:
      'For Maison+Objet\'s "British Capsule," Lee Broom includes a new collection of lighting, as well a selection of complementary furniture and decor.',
    category: 'home furnishing',
    heading: '',
    mainImage: '/images/Lee-Broom-MaisonObjet.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 20,
    title: 'The Design Milk X Modenus Talks Lounge Returns to KBIS 2023',
    description:
      "The Design Milk X Modenus Talks Lounge is back at KBIS with a schedule that's jam-packed full of presentations + conversations covering design business, social media + trends.",
    category: 'featured',
    heading: '',
    mainImage: '/images/Marvila-Attic-Lisbon-KEMA.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 21,
    title:
      'Hotel Riomar Ibiza Celebrates Orange + Neutrals Inspired by Its Surroundings',
    description:
      'Hotel Riomar is a boutique hotel in Ibiza that embraces its mid-century layered interiors by celebrating the nostalgic qualities of its past.',
    category: 'travel',
    heading: 'last launches',
    mainImage: '/images/hotel-riomar.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 22,
    title:
      'An Abandoned Lisbon Attic Becomes Airy Apartment With Hidden Kitchen',
    description:
      'KEMA studio transformed the unlivable MARVILA ATTIC into a bright and airy apartment with a hidden kitchen and built-in wall sofa.',
    category: 'architecture',
    heading: 'last launches',
    mainImage: '/images/The-Home-Lamp.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 23,
    title: 'Desktop Wallpaper: February 2023',
    description:
      "Design Milk's founder Jaime Derringer collaborates with Eskayel on a new mural wallpaper + fabric collection – download one for your desktop wallpaper!",
    category: 'art',
    heading: 'last launches',
    mainImage: '/images/February-2023-Desktop-Wallpaper.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 24,
    title: "Vipp's New Pedal Bin Is Rubbish – Literally!",
    description:
      "The Rubbish special edition of their iconic pedal bin design is made from plastic leftovers and sawdust from Vipp's own production waste.",
    category: 'home furnishing',
    heading: 'last launches',
    mainImage: '/images/Rubbish-Waste-Bin-Recycled.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },

  {
    id: 25,
    title:
      'F5: Paper Artist Zoe Bradley Shares a Go-To Pen, Favorite Liqueur + More',
    description:
      'In this Friday Five, Wales-based paper artist Zoe Bradley shares an inspiring collaboration, go-to pen, a new favorite liqueur, and more.',
    category: 'art',
    heading: 'last launches',
    mainImage: '/images/F5-Zoe-Bradley.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 26,
    title: 'The Oru Collection Brings the Rounded Furniture Trend To Contract',
    description:
      "The influence of the 1970s + Japanese design create a feeling that's bold + iconic in the Oru collection for contract from Patricia Urquiola for Andreu World.",
    category: 'commercial',
    heading: 'popular',
    mainImage: '/images/Andreu-World-Oru-Collection.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 27,
    title:
      'Wire Grids Visually Break up the Open Layout of This Flatiron Office',
    description:
      'Office of Tangible Space created a bright, airy, and inviting new interior with custom solutions for the new ScienceIO headquarters.',
    category: 'commercial',
    heading: 'popular',
    mainImage: '/images/Office-of-Tangible-Space.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 28,
    title: "A 1940s Pink Villa Becomes New Home for Luca Nichetto's Studio",
    description:
      "Luca Nichetto renovated a 40s pink villa to become his Stockholm studio that's curious pink outside with an interior that draws you in.",
    category: 'interrior design',
    heading: 'popular',
    mainImage: '/images/Pink-Villa-Design-Studio.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 29,
    title: 'Smile Plastics Turns Yogurt Pots Into Terrazzo-Like Surface Panels',
    description:
      'Smile Plastics designs and manufactures hand-crafted, supersized terrazzo-like panels for retail, architecture, interiors, and product design – from waste.',
    category: 'home furnishing',
    heading: 'popular',
    mainImage: '/images/GAN_LONDON-STORE.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
  {
    id: 30,
    title:
      'Why Sustainability Will Be the Single Topic at Design China Beijing 2022',
    description:
      "This year's event, also known as Sustainable Design China Summit, will cover the world of design through a sustainability lens.",
    category: 'architecture',
    heading: 'popular',
    mainImage: '/images/design-china-beijing.jpg',
    images: [''],
    content: [''],
    date: '',
    author: '',
    photographer: '',
  },
]

export const getArticlesObject = (array: Article[]) =>
  array.reduce(
    (object, article) => ({
      ...object,
      [article.id]: article,
    }),
    {}
  )

export default ArticlesArray
